permissions:
  contents: write

steps:
  - uses: actions/checkout@v4
    with:
      token: ${{ secrets.GH_TOKEN }}

  - name: Git config
    run: |
      git config user.name "aurora-light"
      git config user.email "1983292042@qq.com"

  - name: Update blog files
    run: |
      pnpm run sync-post
      git add .
      git commit -m 'chore(ci): blog sync' || echo "no changes"

  - name: Rebase
    run: git pull --rebase origin main || true

  - name: Use PAT
    run: |
      git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

  - name: Push
    run: git push origin HEAD:main
